export const  CAMPUS_GROUP_ROUTE ='/groups'
export const  LOGIN_ROUTE ='/login'
export const  REGISTRATION_ROUTE ='/registration'
export const  MAIN_PAGE_ROUTE ='/'
export const  PROFILE_ROUTE ='/profile'
export const  MY_COURSES ='/courses/my'
export const  MY_TEACHING_COURSES ='/courses/teaching'